name: Workflow

on: 
 push:
    branches: -master
 workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
    - name: Synchronize Git repository to uberspace
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-avz"
        SERVER_PORT: 8080
        FOLDER: "./"
        SERVER_IP: daniloradulovic@10.251.82.248:/Desktop/
        USERNAME: " daniloradulovic"
        SERVER_DESTINATION: ./Desktop
