name: Workflow

on: 
 push:
    branches: -master
 workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -   name: Setup SSH Keys and known_hosts
        env:
         SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
                    mkdir -p ~/.ssh
                    ssh-keyscan github.com >> ~/.ssh/known_hosts
                    ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                    ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"


       
    - name: Synchronize Git repository to uberspace
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-avz"
        SERVER_PORT: 22
        FOLDER: "./"
        SERVER_IP: ${{ secrets.SSH_HOST }}
        USERNAME: " daniloradulovic"
        SERVER_DESTINATION: ./Desktop
