name: DEPLOY
on:
  push:
    branches:
    - master

  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        
        
    - name: Rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: /
        #remote_path: /
        #remote_host: 127.0.0.1
        #remote_port: 8080
        #remote_user: daniloradulovic@Danilos-Mac-mini.local
        #remote_key: 

