name: DEPLOY
on:
  push:
    branches:
    - master

  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ../..
        remote_path: /var/www/
        remote_host: daniloradulovic.com
        remote_user: debian
        remote_key: ${{ secrets.DEPLOY_KEY }}
